using System.ComponentModel;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.SemanticKernel;
using SmartErpAgent.Application.Common.Interfaces;
using SmartErpAgent.Application.DTOs;
using SmartErpAgent.Core.Entities;
using SmartErpAgent.Core.Enums;

namespace SmartErpAgent.AgentEngine.Plugins;

public class PurchaseOrderAgentPlugin
{
    private readonly IApplicationDbContext _dbContext;

    public PurchaseOrderAgentPlugin(IApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    [KernelFunction, Description("Scans tenant inventory to identify all products where stock quantity is at or below the safety reorder threshold, returning SKU, name, current stock, threshold, suggested replenishment quantity, unit price, and estimated restock cost.")]
    public async Task<string> GetLowStockAlertsAsync(CancellationToken cancellationToken = default)
    {
        var lowStockItems = await _dbContext.InventoryItems
            .Where(i => i.IsActive && i.StockQuantity <= i.ReorderThreshold)
            .OrderBy(i => i.StockQuantity - i.ReorderThreshold)
            .ToListAsync(cancellationToken);

        var alerts = lowStockItems.Select(item =>
        {
            var targetStock = item.ReorderThreshold * 2;
            var suggestedReorderQuantity = Math.Max(1, targetStock - Math.Max(0, item.StockQuantity));
            var estimatedCost = suggestedReorderQuantity * item.UnitPrice;

            return new LowStockAlertDto(
                SKU: item.SKU,
                Name: item.Name,
                StockQuantity: item.StockQuantity,
                ReorderThreshold: item.ReorderThreshold,
                SuggestedReorderQuantity: suggestedReorderQuantity,
                UnitPrice: item.UnitPrice,
                EstimatedRestockCost: estimatedCost
            );
        }).ToList();

        return JsonSerializer.Serialize(new
        {
            TotalLowStockItems = alerts.Count,
            TotalEstimatedCost = alerts.Sum(a => a.EstimatedRestockCost),
            Alerts = alerts
        }, new JsonSerializerOptions { WriteIndented = true });
    }

    [KernelFunction, Description("Autonomously generates and saves a draft Purchase Order (status: Draft) to replenish low-stock inventory items. Can target specific comma-separated SKUs or automatically replenish all depleted items.")]
    public async Task<string> CreateDraftPurchaseOrderAsync(
        [Description("Optional comma-separated list of product SKUs to replenish. If omitted or empty, all low-stock items will be replenished.")] string? targetSkus = null,
        CancellationToken cancellationToken = default)
    {
        IQueryable<InventoryItem> query = _dbContext.InventoryItems.Where(i => i.IsActive);

        HashSet<string>? skuSet = null;
        if (!string.IsNullOrWhiteSpace(targetSkus))
        {
            skuSet = targetSkus
                .Split(new[] { ',', ';', ' ' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(s => s.ToLowerInvariant())
                .ToHashSet();

            query = query.Where(i => skuSet.Contains(i.SKU.ToLower()));
        }
        else
        {
            query = query.Where(i => i.StockQuantity <= i.ReorderThreshold);
        }

        var candidateItems = await query.ToListAsync(cancellationToken);

        if (candidateItems.Count == 0)
        {
            var emptyResult = new DraftPurchaseOrderResultDto(
                Success: false,
                PurchaseOrderId: null,
                OrderNumber: string.Empty,
                SupplierName: string.Empty,
                OrderDate: DateTime.UtcNow,
                TotalAmount: 0m,
                Currency: "USD",
                Status: "None",
                LineItemCount: 0,
                LineItems: new List<PurchaseOrderLineItemDto>(),
                Message: "No inventory items require replenishment at this time."
            );

            return JsonSerializer.Serialize(emptyResult, new JsonSerializerOptions { WriteIndented = true });
        }

        var existingPoCount = await _dbContext.PurchaseOrders.CountAsync(cancellationToken);
        var orderNumber = $"PO-{DateTime.UtcNow:yyyyMM}-{(existingPoCount + 1):D4}";

        var purchaseOrder = new PurchaseOrder
        {
            OrderNumber = orderNumber,
            SupplierName = "Primary Replenishment Supplier",
            OrderDate = DateTime.UtcNow,
            ExpectedDeliveryDate = DateTime.UtcNow.AddDays(7),
            Currency = "USD",
            Status = PurchaseOrderStatus.Draft,
            Notes = "Autonomously generated by Smart ERP Purchase Order Agent Copilot"
        };

        decimal totalAmount = 0m;
        var lineItemDtos = new List<PurchaseOrderLineItemDto>();

        foreach (var item in candidateItems)
        {
            var targetStock = item.ReorderThreshold * 2;
            var replenishQty = Math.Max(1, targetStock - Math.Max(0, item.StockQuantity));
            var lineTotal = replenishQty * item.UnitPrice;
            totalAmount += lineTotal;

            var lineItem = new PurchaseOrderLineItem
            {
                InventoryItemId = item.Id,
                SKU = item.SKU,
                ItemName = item.Name,
                Quantity = replenishQty,
                UnitPrice = item.UnitPrice,
                TotalPrice = lineTotal,
                PurchaseOrder = purchaseOrder
            };

            purchaseOrder.LineItems.Add(lineItem);

            lineItemDtos.Add(new PurchaseOrderLineItemDto(
                Id: lineItem.Id,
                InventoryItemId: item.Id,
                SKU: item.SKU,
                ItemName: item.Name,
                Quantity: replenishQty,
                UnitPrice: item.UnitPrice,
                TotalPrice: lineTotal
            ));
        }

        purchaseOrder.TotalAmount = totalAmount;

        _dbContext.PurchaseOrders.Add(purchaseOrder);
        await _dbContext.SaveChangesAsync(cancellationToken);

        var resultDto = new DraftPurchaseOrderResultDto(
            Success: true,
            PurchaseOrderId: purchaseOrder.Id,
            OrderNumber: purchaseOrder.OrderNumber,
            SupplierName: purchaseOrder.SupplierName,
            OrderDate: purchaseOrder.OrderDate,
            TotalAmount: purchaseOrder.TotalAmount,
            Currency: purchaseOrder.Currency,
            Status: purchaseOrder.Status.ToString(),
            LineItemCount: purchaseOrder.LineItems.Count,
            LineItems: lineItemDtos,
            Message: $"Draft Purchase Order {orderNumber} created successfully with {purchaseOrder.LineItems.Count} line items totaling ${totalAmount:N2}."
        );

        return JsonSerializer.Serialize(resultDto, new JsonSerializerOptions { WriteIndented = true });
    }
}
